#ifndef USER_ACCOUNT_H
#define USER_ACCOUNT_H

#include <string>
#include "Wallet.h"

class UserAccount {
private:
    std::string username;
    std::string hashed_password;
    std::string full_name;
    std::string email;
    bool is_manager;
    bool is_password_auto_generated;
    Wallet wallet;

public:
    UserAccount() = default;

    UserAccount(const std::string& uname,
                const std::string& hashed_pw,
                const std::string& fullname,
                const std::string& email_addr,
                bool manager,
                bool auto_gen_pw);

    const std::string& getUsername() const;
    bool checkPassword(const std::string& pw) const;
    void setPassword(const std::string& pw, bool auto_gen = false);
    bool getIsPasswordAutoGenerated() const;
    void setIsPasswordAutoGenerated(bool val);

    const std::string& getFullName() const;
    void setFullName(const std::string& name);

    const std::string& getEmail() const;
    void setEmail(const std::string& email);

    bool isManager() const;

    Wallet& getWallet();

    void displayInfo() const;

    std::string serialize() const;
    static UserAccount deserialize(const std::string& data_line);
};

#endif
